{
    'name': 'XINK - Sale - Product Custom',
    'version': '1.0',
    'summary': 'Custom The product information',
    'author': 'Xink Tech - Xink SJG',
    'license': 'LGPL-3',
    'category': 'Xink-Tools',
    'depends': ['base', 'product', 'stock','sale'],
    'data': [
        'views/hide_item_product.xml',
        'views/hide_item_product_tab_sale.xml',
        'views/hide_item_product_variants.xml',
        'views/hide_item_product_variants_tab_sale.xml',
        'views/hide_chatter_buttons_product_sale.xml',
        'views/hide_chat_box.xml',
        'views/hide_view_diagram_product.xml',
        'views/product_template_form_inherit_invoiceable.xml',
        'views/sale_order_line_view.xml',
        'views/product_pricelist_custom.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'product_custom/static/src/js/is_invoiceable_icon.js',
            'product_custom/static/src/xml/is_invoiceable_icon.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': True,
}
