{
    'name': 'Xink Purchase',
    'version': '18.0.1.0.0',
    'category': 'Purchases',
    'summary': 'Tích hợp Đề xuất mua hàng, Đánh giá nhà cung cấp, và Mẫu đánh giá',
    'author': 'Your Company',
    'depends': ['base', 'purchase', 'hr', 'mail', 'product'],
    'data': [
        'security/ir.model.access.csv',
        'data/purchase_proposal_sequence.xml',
        'data/supplier_evaluation_sequence.xml',
        'data/vendor_code_sequence.xml',
        'views/hide_menu.xml',
        'views/purchase_proposal_views.xml',
        'views/purchase_order_proposal_view.xml',
        'views/supplier_evaluation_views.xml',
        'views/evaluation_template_views.xml',
        'views/res_partner_views.xml',
        'views/purchase_rfq_custom.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'xink_purchase/static/src/js/score_buttons_widget.js',
            'xink_purchase/static/src/xml/score_buttons_widget.xml',
            'xink_purchase/static/src/css/score_buttons.css',
            'xink_purchase/static/src/css/state_badge.css',
            'xink_purchase/static/src/css/supplier_evaluation.css',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'auto_install': False,
}