{
    'name': 'XINK - Sale - Custom Menu_Screen',
    'version': '1.0',
    'summary': 'Custom Menu/ShowHide input/button',
    'author': 'Xink Tech - Xink SJG',
    'license': 'LGPL-3',
    'category': 'Xink-Tools',
    'depends': ['base', 'sale', 'sale_loyalty', 'loyalty', 'web','sale_pdf_quote_builder', 'sale_management','mail', 'account'],
    'data': [
        'views/hide_config_menu.xml',
        'views/hide_sale_invoicing_menu.xml',
        'views/hide_menu_reports.xml',
        'views/custome_menu_reports.xml',
        'views/hide_optional_and_signature.xml',
        'views/hide_fields_incoterm.xml',
        'views/hide_chat_bot.xml',
        'views/custom_sale_person.xml',
        'views/hide_country_group.xml',
        'views/menu_order_custom.xml',
        'views/hide_ewallet_custom.xml',
        'views/sale_order_price_unit_restrict.xml',
        'views/sale_order_price_unit_hide_for_manager.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sale_custom/static/src/css/hide_upload_button.css',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': True,
}
